name: Build PR image

on:
  pull_request:
    branches:
      - 'main'

env:
  DOCKERFILE_TAG: ${{ github.event.pull_request.head.sha }}
  DOCKERFILE: Dockerfile-debian

jobs:
  build-image:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Github Packages
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Get Atlantis version
        id: atlantis-version
        shell: bash
        run: |
          echo "ATLANTIS_VERSION=$(grep "ARG ATLANTIS_VERSION" $DOCKERFILE | cut -d "=" -f2)" >> "$GITHUB_OUTPUT"

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v3
        with:
          images: |
            ghcr.io/lablabs/atlantis
          # generate Docker tags based on the following events/attributes
          tags: |
            type=raw,prefix=${{ steps.atlantis-version.outputs.ATLANTIS_VERSION }},value=${{ github.event.pull_request.head.sha }}

#      - name: Build image and push to GitHub Container Registry
#        uses: docker/build-push-action@v3
#        with:
#          context: .
#          file: ./${{ end.DOCKERFILE }}
#          platforms: linux/amd64,linux/arm64
#          tags: ${{ steps.meta.outputs.tags }}
#          labels: ${{ steps.meta.outputs.labels }}
#          push: true