name: Build PR image

on:
  pull_request:
    branches:
      - 'main'
    paths:
      - 'Dockerfile*'
      - 'version'

jobs:
  build-image:
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        os:
          - debian
         # - alpine
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Lint Dockerfile
        id: hadolint
        uses: hadolint/hadolint-action@v3.1.0
        with:
          dockerfile: "./Dockerfile-${{ matrix.os }}"
          failure-threshold: warning

      - name: Get Atlantis version
        id: atlantis-version
        shell: bash
        run: |
          echo "ATLANTIS_VERSION=$(cat version)" >> "$GITHUB_OUTPUT"

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Github Packages
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v3
        with:
          images: |
            ghcr.io/lablabs/atlantis
          # generate Docker tags based on the following events/attributes
          tags: |
            type=raw,value=${{ steps.atlantis-version.outputs.ATLANTIS_VERSION }}-${{ github.event.pull_request.head.sha }}-${{ matrix.os }}
            type=raw,value=${{ steps.atlantis-version.outputs.ATLANTIS_VERSION }}-pr${{ github.event.number }}-alpha-${{ matrix.os }}

      - name: Build image and push to GitHub Container Registry
        uses: docker/build-push-action@v3
        with:
          context: .
          build-args: |
            ATLANTIS_VERSION=${{ steps.atlantis-version.outputs.ATLANTIS_VERSION }}
          file: ./Dockerfile-${{ matrix.os }}
          platforms: linux/amd64,linux/arm64
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          push: true
